openapi: 3.0.4
info:
  title: Morse Code
  description: >-
    Morse Code is a simple tool for encoding and decoding Morse code. It returns
    the encoded or decoded Morse code.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.0
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
  - url: https://api.apiverve.com/
paths:
  /v1/morsecode:
    post:
      summary: Encode Morse Code
      description: >-
        Morse Code is a simple tool for encoding and decoding Morse code. It
        returns the encoded or decoded Morse code.
      operationId: morsecode
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: object
                    description: data
              example:
                status: ok
                error: null
                data:
                  text: This Is A Message
                  morse: '- .... .. ... / .. ... / .- / -- . ... ... .- --. . '
                  stats:
                    characters: 17
                    dits: 25
                    dahs: 7
                  valid: true
                  audio:
                    audioFile: a11f9d7f-1fd2-4b10-86de-82defaf18c57.wav
                    format: .wav
                    downloadURL: >-
                      https://storage.googleapis.com/apiverve/APIData/morsecode/a11f9d7f-1fd2-4b10-86de-82defaf18c57.wav?GoogleAccessId=635500398038-compute%40developer.gserviceaccount.com&Expires=1765925804&Signature=TiktgUsHV0ipCaRwNNiEihtD5e1SacBHBwWLGvsrnLJTkH%2BH5fRsII5hxk7nEqTypya05Dg4BHTxu672tRU%2Bhb3F8g%2BQYL7u3PMaCHzcnrrpcjSh0hH7%2BWVfEyHxPf5cCuKliISePCOlpbVsU8xtFL8p1DfgTV2FeD8Rmwo3SVpCG4LHpYXJWoZVET2IbS4dZS%2Brn9kvnoBvApgDJgc5EEufOZHYLba6278g0HTgQaOIhdSNhpeSpCwPuSw6q3eK%2FGqzhD5PtzTBMPN1hMvXIZPX11EYRG%2FLbqvltu6gVgbYL5khcG5zQbDse2vXphAys8fMq7PiZSGe1ODf63Gakw%3D%3D
                    duration: 13.20s
                    frequency: 600Hz
                    sampleRate: 8000Hz
                    expires: 1765925804517
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occurred, try again later
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The text to encode or decode in Morse code
                audio:
                  type: boolean
                  description: Set to true to include an audio file of the Morse code
              required:
                - text
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
  - api_key: []
sampleRequest:
  audio: true
  text: This Is A Message
