openapi: 3.0.4
info:
  title: Morse Code
  description: Morse Code is a simple tool for encoding and decoding Morse code. It returns the encoded or decoded Morse code.
  termsOfService: https://apiverve.com/terms/
  contact:
    name: APIVerve Support
    email: hello@apiverve.com
    url: https://apiverve.com/contact
  version: 1.0.9
externalDocs:
  description: Learn more about APIVerve
  url: https://docs.apiverve.com?utm_source=openapi
servers:
- url: https://api.apiverve.com/
paths:
  /v1/morsecode:
    post:
      summary: Encode Morse Code
      description: Morse Code is a simple tool for encoding and decoding Morse code. It returns the encoded or decoded Morse code.
      operationId: morsecode
      parameters: []
      responses:
        '200':
          description: Successful Response
          content:
            application/json:
              schema:
                type: object
                properties:
                  status:
                    type: string
                    description: status
                  error:
                    type: string
                    description: error
                  data:
                    type: string
                    description: data
              example:
                status: ok
                error: 
                data:
                  text: This Is A Message
                  morse: '- .... .. ... / .. ... / .- / -- . ... ... .- --. . '
                  stats:
                    characters: 17
                    dits: 25
                    dahs: 7
                  valid: true
                  audio:
                    audioFile: 9187cc09-7f1c-4ef6-91b2-47b45a779d37.wav
                    format: .wav
                    downloadURL: https://storage.googleapis.com/apiverve.appspot.com/morsecode/9187cc09-7f1c-4ef6-91b2-47b45a779d37.wav?GoogleAccessId=635500398038-compute%40developer.gserviceaccount.com&Expires=1760978073&Signature=msdNuo4gid8r%2F89Tkuo9ybJOh2qccrs9ceqDXX4QAmeTMVNVwqWeLh1ULL2%2BXQAo4p%2FBav7x7K7xIJQyDFqyIMsqlZnSopGHvaFAKLF7K%2BJZlZORk3XrG0KN2VvvTrGWbOLytOdPa8xlxYeWNQZjA48QyNCWgDEG5ovLcbS3HWrPM%2BYz4yE80MV60eb6orHaA0%2FQsVuPAKNYta1GwcyXWGU7HzP8gAUhf6tdsG6bdvcv7Vs92iKv0fSKxxsHiziVe6zQQOKqAzMtzTg9RnujEVksCiq7KzRMsSLKizWBLRvPokEpbaydds8N%2B35fQztmnykFCQ2RDXxxoHQsB2fZzQ%3D%3D
                    duration: 13.20s
                    frequency: 600Hz
                    sampleRate: 44100Hz
                    expires: 1760978073054
        '401':
          description: Your request was not authorized, or your API Key was invalid
        '404':
          description: Requested resource was not found
        '500':
          description: A server error has occured, try again later
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                text:
                  type: string
                  description: The text to encode or decode in Morse code
                  example: This Is A Message
              required:
              - text
              example:
                audio: true
                text: This Is A Message
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: x-api-key
      in: header
security:
- api_key: []
